name: Build and Lint

on: [pull_request]

concurrency:
  group: pr-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check:
    uses: apexskier/homebridge-workflows/.github/workflows/check.yml@main
